spring:
  application:
    name: service-discovery
security:
  basic:
    enabled: true
  user:
    name: user
    password: password
server:
  port: 8761
  use-forward-headers: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  server:
    enableSelfPreservation: true

